---
- name: install docker on CentOS
  hosts: centos
  gather_facts: no
  become: yes

  tasks:
    - name: Download the Docker installer
      get_url : https://get.docker.com | sh

    - name: Install docker
      yum: name=docker state=latest

    - name: Start Docker service
      service: name=docker state=started enabled=yes

    - name: Pull default Docker image
      docker_image:
        name: edowon0623/my-user-service:1.1
        source: pull


- name: install docker on Ubuntu
  hosts: ubuntu
  gather_facts: no
  become: yes

  tasks:
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker
      apt: update_cache=yes name=docker state=latest

    - name: Start Docker service
      service: name=docker state=started enabled=yes

    - name: Pull default Docker image
      docker_image:
        name: edowon0623/my-user-service:1.1
        source: pull