---
- name: install nginx on CentOS
  hosts: centos
  gather_facts: no
  become: yes

  tasks:
    - name: install epel-release
      yum: name=epel-release state=latest
    - name: install nginx web server
      yum: name=nginx state=present
    - name: upload default index.html for web server
      get_url: url=https://www.nginx.com dest=/usr/share/nginx/html/
    - name: start nginx web server
      service: name=nginx state=started

- name: install nginx on Ubuntu
  hosts: ubuntu
  gather_facts: no
  become: yes

  tasks:
    - name: install nginx web server
      apt: pkg=nginx state=present update_cache=yes
    - name: upload default index.html for web server
      get_url: url=http://www.apache.com dest=/usr/share/nginx/html/ validate_certs=no
    - name: start nginx web server
      service: name=nginx state=started